language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Wt
  - sudo ./install_wt

services:
  - xvfb

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14_wt &
  - sleep 10
  - sudo killall travis_qmake_gcc_cpp14_wt

