language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Wt
  - sudo apt-get install witty witty-dbg witty-dev witty-doc

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14_wt &
  - sleep 10
  - sudo killall travis_qmake_gcc_cpp14_wt

